import NextHead from 'next/head'
import React, { ReactElement } from 'react'

function Head(): ReactElement {
  return (
    <NextHead>
      <meta name="description" content="Generated by create next app" />
      <meta name="viewport" content="width=device-width, initial-scale=1" />
    </NextHead>
  )
}

export default Head
