import '../styles/globals.scss'

import type { AppProps } from 'next/app'
import Head from 'next/head'
import Navbar from '@/components/layout/navbar'
import Sidebar from '@/components/layout/sidebar'

function MyApp({ Component, pageProps }: AppProps) {
  return (
    <>
      <Head>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <Navbar />
      <div className="row">
        <div className="col-2">
          <Sidebar />
        </div>
      </div>
      <Component {...pageProps} />
    </>
  )
}
export default MyApp
