import '../styles/globals.scss'

import type { AppProps } from 'next/app'
import Head from 'next/head'

import Navbar from '@/components/layout/navbar'
import Sidebar from '@/components/layout/sidebar'
import ReduxProviderWrapper from '@/redux/ProviderWrapper'

function MyApp(props: AppProps) {
  const { Component, pageProps } = props

  return (
    <>
      <Head>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <ReduxProviderWrapper>
        <Navbar />
        <div className="row">
          <div className="col-2">
            <Sidebar />
          </div>
        </div>
        <Component {...pageProps} />
      </ReduxProviderWrapper>
    </>
  )
}
export default MyApp
